repos:
  - repo: local
    hooks:
      - id: bracketize-sql
        name: Bracketize SQL Identifiers
        entry: python scripts/bracketize_sql.py
        language: python
        types: [sql]
        pass_filenames: true

      - id: sqlfluff-fix
        name: SQLFluff Auto-Fix
        entry: sqlfluff fix
        language: system
        types: [sql]
        pass_filenames: true
