repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
  - repo: local
    hooks:
      # - id: bracketize-sql
      #   name: Bracketize SQL Identifiers
      #   entry: python scripts/bracketize_sql.py
      #   language: python
      #   types: [sql]
      #   pass_filenames: true
      #   additional_dependencies:
      #     - sqlglot==27.16.3

      - id: sqlfluff-fix
        name: SQLFluff Auto-Fix
        entry: sqlfluff fix --show-lint-violations
        language: python
        types: [sql]
        pass_filenames: true
        additional_dependencies:
          - sqlfluff==3.4.2
